version: '3'

services:
  php:
    build: 
      context: docker/php
      args:
        APP_NAME: $APP_NAME
    ports: ['8000:8000'] 
    tty: true
    volumes:
      - ./${APP_NAME}:/var/www/${APP_NAME}
      - $HOME/.gitconfig:/root/.gitconfig
    working_dir: /var/www/${APP_NAME}
    env_file: ./.env

