version: '3'

services:
  php:
    build: 
      context: docker/php
      args:
        APP_NAME: $APP_NAME
    ports: ['8000:8000'] 
    tty: true
    volumes:
      - ./${APP_NAME}:/var/www/${APP_NAME}
      - $HOME/.gitconfig:/root/.gitconfig
    working_dir: /var/www/${APP_NAME}
    env_file: ./${APP_NAME}/.env
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]
